name: Test

on:
  workflow_dispatch:
    # inputs:
    #   template:
    #     type: string
    #     description: template (.github/PROJECT_TEMPLATES/)
    #     required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: release
      uses: jefeish/create-release@main
      id: create_release
      with:
        tag_name: Tag ${{ env.GITHUB_RUN_NUMBER }}
        release_name: Release ${{ env.GITHUB_RUN_NUMBER }}
        body_path: ./CHANGELOG.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
